# Generated by Django 3.1.7 on 2021-02-20 15:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=250)),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('new', models.BooleanField(blank=True, default=True)),
                ('mahasale', models.BooleanField(blank=True, default=False)),
                ('image', models.ImageField(upload_to='product/')),
                ('Original_price', models.DecimalField(decimal_places=0, default=0, max_digits=16)),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now)),
                ('tag', models.TextField(blank=True, default=None, null=True)),
                ('color', models.TextField(blank=True, default=None, null=True)),
                ('size', models.TextField(blank=True, default=None, null=True)),
                ('stock', models.IntegerField(default=0)),
                ('variation', models.TextField(blank=True, default=None, null=True)),
                ('fashion', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('material', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('feature', models.CharField(blank=True, default=None, max_length=2500, null=True)),
                ('point_desc', models.TextField(blank=True, default=None, null=True)),
                ('short_desc', models.CharField(blank=True, default=None, max_length=5000, null=True)),
                ('long_desc', models.TextField(blank=True, default=None, null=True)),
                ('weight', models.IntegerField(blank=True, default=0, null=True)),
                ('rating', models.SmallIntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product/')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='productImages', to='product.product')),
            ],
        ),
    ]
