# Generated by Django 3.1.7 on 2021-02-27 05:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210227_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='point_desc',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True),
        ),
    ]
