# Generated by Django 3.1.7 on 2021-02-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_products', models.CharField(default=0, max_length=500)),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=16)),
                ('transaction_id', models.CharField(default=0, max_length=150)),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=16)),
                ('transaction_status', models.CharField(default=0, max_length=250)),
                ('payment_status', models.BooleanField(default=False)),
                ('order_confirm', models.BooleanField(default=False)),
                ('order_shipped', models.BooleanField(default=False)),
                ('delivery', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
